(define (main)
  (display (first 1 2 3))
  (newline)
  (display (second 1 2 3))
  (newline)
  (display (third 1 2 3))
  (newline)
  (return 107))

(define (first x y z) (return x))
(define (second x y z) (return y))
(define (third x y z) (return z))
